services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack-user-service
    ports:
      - "6380:6380"
      - "8002:8002"
